// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
)

type Author struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	InsertedAt sql.NullTime   `json:"insertedAt"`
}

type Book struct {
	ID          int64          `json:"id"`
	Name        sql.NullString `json:"name"`
	Year        sql.NullInt32  `json:"year"`
	AuthorID    sql.NullInt64  `json:"author_id"`
	Summary     sql.NullString `json:"summary"`
	PublisherID sql.NullInt64  `json:"publisher_id"`
	PageCount   sql.NullInt32  `json:"pageCount"`
	ReadPage    sql.NullInt32  `json:"readPage"`
	Finished    sql.NullBool   `json:"finished"`
	Reading     sql.NullBool   `json:"reading"`
	InsertedAt  sql.NullTime   `json:"insertedAt"`
	UpdatedAt   sql.NullTime   `json:"updatedAt"`
}

type Publisher struct {
	ID         int64          `json:"id"`
	Name       sql.NullString `json:"name"`
	InsertedAt sql.NullTime   `json:"insertedAt"`
}
