// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"database/sql"
	"time"
)

type Author struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	InsertedAt time.Time `json:"insertedAt"`
}

type Book struct {
	ID          int64        `json:"id"`
	Name        string       `json:"name"`
	Year        int32        `json:"year"`
	AuthorID    int64        `json:"author_id"`
	Summary     string       `json:"summary"`
	PublisherID int64        `json:"publisher_id"`
	PageCount   int32        `json:"pageCount"`
	ReadPage    int32        `json:"readPage"`
	Finished    bool         `json:"finished"`
	Reading     bool         `json:"reading"`
	InsertedAt  time.Time    `json:"insertedAt"`
	UpdatedAt   sql.NullTime `json:"updatedAt"`
}

type Publisher struct {
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	InsertedAt time.Time `json:"insertedAt"`
}
